### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BryanThePotato** [Developer-Doge/Fox-Origin#16]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wiicustomorigins'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$2751/1867096421.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: WIDTH
	at wiicustomorigins.common.registry.EOScaleTypes.<clinit>(EOScaleTypes.java:14)
	at wiicustomorigins.common.WiiCustomOrigins.onInitialize(WiiCustomOrigins.java:13)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2245/1334679764.accept(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more

**Comment by Developer-Doge** [comment]
Should be fixed with 1.19.4 update.
